### ISSUE TITLE
Adding backtracking questions in Love babbar DSA sheet

### ISSUE THREAD

**Issue by saiteja-2731** [thepranaygupta/Data-Structures-and-Algorithms#101]
Hello, I have gone through Love babbar folder in your profile and I came to know that many of the sub-folders i.e Linked lists, Backtracking, etc are empty. Will it be okay to add backtracking solutions from love babbar DSA sheet?

**Comment by thepranaygupta** [comment]
suree go for it!!
assigned to @saiteja-2731

**Comment by saiteja-2731** [comment]
Thankyou @thepranaygupta
