### ISSUE TITLE
Best Time to buy and sell stock

### ISSUE THREAD

**Issue by mukeshmjn** [thepranaygupta/Data-Structures-and-Algorithms#110]
@thepranaygupta please assign this to me

**Comment by 8-bit-souvik** [comment]
best of luck @mukeshmjn

**Comment by mukeshmjn** [comment]
@8-bit-souvik i have made some pull request can u merge it

**Comment by mukeshmjn** [comment]
#108
#107
#103   @8-bit-souvik

**Comment by HatimTai1** [comment]
Sir I would like to solve this. Kindly assign me this issue.

**Comment by thepranaygupta** [comment]
> 
> 
> Sir I would like to solve this. Kindly assign me this issue.

sorry @HatimTai1 this issue was already assigned to @mukeshmjn and it'll be closed now

**Comment by 8-bit-souvik** [comment]
> Sir I would like to solve this. Kindly assign me this issue.

Sorry @HatimTai1 there was a misunderstanding, the PR regarding to this issue is already merged. But you can raise an issue or work on other unassigned one.
