### ISSUE TITLE
Pick from both sides - Array Problem

### ISSUE THREAD

**Issue by K1RA-16** [thepranaygupta/Data-Structures-and-Algorithms#122]
This is an interview bit problem and i would like to add it into the array folder for algorithms.
I ll be doing the problem in c++.
This is my effort to raise a pull request for hacktoberfest.

**Comment by K1RA-16** [comment]
https://www.interviewbit.com/problems/pick-from-both-sides/

**Comment by thepranaygupta** [comment]
assigned to @K1RA-16 !!
