### ISSUE TITLE
Hii, I wanted to add famous interview problem Majority Element

### ISSUE THREAD

**Issue by rushikeshadhav** [thepranaygupta/Data-Structures-and-Algorithms#133]
Please assign me this.
This question is asked in many interviews. 
I need this for hacktoberfest.

**Comment by MuskanGupta1503** [comment]
Can I work on this.. please

**Comment by thepranaygupta** [comment]
assigned to @rushikeshadhav 👍

**Comment by thepranaygupta** [comment]
> 
> 
> Can I work on this.. please

Sorry @MuskanGupta1503 we are assigning issues on a First Come First Serve basis, please consider creating a new issue if you wish to contribute. 😄

**Comment by rushikeshadhav** [comment]
@thepranaygupta Added the majority element problem. Kindly merge.
