### ISSUE TITLE
add solutions of Linked List problems

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#14]
add solutions of Linked List problems [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/01.%20Linked%20List/1.%20Singly-Linked-List/InterviewBit%20Questions)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by anandhu720** [comment]
can added cpp solution for reverse a linked list

**Comment by subhamengine** [comment]
ill be doing

**Comment by thepranaygupta** [comment]
yes go for it @anandhu720 and @subhamengine

**Comment by anandhu720** [comment]
added a pr,can you check it please
@thepranaygupta

**Comment by LakshitXD** [comment]
can i submit in pyhon or any other language?

**Comment by aguyran** [comment]
Can I get this assigned for some solutions in languages like python or js ?

**Comment by thepranaygupta** [comment]
> 
> 
> can i submit in pyhon or any other language?

yes @LakshitXD you can add your python code

**Comment by thepranaygupta** [comment]
> 
> 
> Can I get this assigned for some solutions in languages like python or js ?

yes @aguyran you can add your JS code

**Comment by anandhu720** [comment]
@thepranaygupta made a pr for reverse LL

**Comment by thepranaygupta** [comment]
> 
> 
> @thepranaygupta made a pr for reverse LL

merged!!
