### ISSUE TITLE
Love Babbar DSA Sheet - Count Strongly Connected Components

### ISSUE THREAD

**Issue by vartikavr** [thepranaygupta/Data-Structures-and-Algorithms#142]
I'll be adding an explanation and solution (in C++) to the problem  - Count Strongly Connected Components using Kosaraju Algorithm. I'll add this under the folder Love Babbar DSA Sheet Solutions/Graph.
Kindly assign this to me.

**Comment by thepranaygupta** [comment]
sure @vartikavr go for it!! 🚀
