### ISSUE TITLE
add C++ implementation of doubly Linked List

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#16]
add C++ implementation of doubly Linked List [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/01.%20Linked%20List/2.%20Doubly-Linked-List/Basic%20Operations)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by PranavDherange** [comment]
I would like to work on this issue
Can u please assign me this issue

**Comment by thepranaygupta** [comment]
sure go for it @PranavDherange
