### ISSUE TITLE
Palindrome List

### ISSUE THREAD

**Issue by K1RA-16** [thepranaygupta/Data-Structures-and-Algorithms#178]
interview bit problem under Linked List
https://www.interviewbit.com/problems/palindrome-list/
Asked in Amazon & Microsoft

**Comment by Priyanshi136** [comment]
@thepranaygupta Hey, can you assign this task to me.

**Comment by K1RA-16** [comment]
Hi @Priyanshi136 actually the question's done and I'm just waiting for his approval to raise a pr so maybe u can try another problem?
Happy coding 💯

**Comment by K1RA-16** [comment]
@thepranaygupta can i go ahead with the pr
???

**Comment by thepranaygupta** [comment]
yes @K1RA-16 you can
