### ISSUE TITLE
most water in the container

### ISSUE THREAD

**Issue by yellowberard** [thepranaygupta/Data-Structures-and-Algorithms#185]
I want to add  the answer for leetcode question - https://leetcode.com/problems/container-with-most-water/
Language-c++
I want to contribute for hacktoberfest21.
Please assign me this issue and appropriate label.

**Comment by Aakash01ak** [comment]
@thepranaygupta If this problem is not done yet. Can you assign this to me .

**Comment by thepranaygupta** [comment]
@yellowberard are you working on this issue?

**Comment by Aritra-20** [comment]
showing this error: invalid path '01. DataStructures/08. Graph/Leetcode Questions/03. Is Graph Bipartite? #785/Is Graph Bipartite.


how to resolve this??
