### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by kumar-tushar** [thepranaygupta/Data-Structures-and-Algorithms#191]
This question is asked by many top companies like Google, Facebook, etc.

Interviewbit Link: https://www.interviewbit.com/problems/rain-water-trapped/

I want to solve this issue in Java.

This is related to Array.

Contributing for Hacktoberfest 2021

**Comment by kumar-tushar** [comment]
This is related to Array

**Comment by kumar-tushar** [comment]
Could I work on this issue @thepranaygupta

**Comment by 8-bit-souvik** [comment]
Thanks for contributing 🎉
