### ISSUE TITLE
implement stacks using array in C++

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#20]
implement stacks using array in C++ [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/02.%20Stack/Basic%20Operation/1.%20Stack%20using%20Array)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by Nidhikumari-4** [comment]
please assign this issue to me

**Comment by rustzz-27** [comment]
Hello,
can you assign this issue to me
Thank you

**Comment by harshchandwani** [comment]
Hell, Please assign it to me.

**Comment by thepranaygupta** [comment]
@rustzz-27 go for it!

**Comment by vaishalijain3456** [comment]
Hello,
Will you please assign me this issue?
Thank You

**Comment by hrigved-dev** [comment]
Hello, I would like to implement Stacks using Array in C++. Would you assign me this issue?

**Comment by rustzz-27** [comment]
> @rustzz-27 go for it!

I have made a pr pls review it 
#99
