### ISSUE TITLE
Maximum Subarray

### ISSUE THREAD

**Issue by sejalrastogi** [thepranaygupta/Data-Structures-and-Algorithms#209]
I want to add java solution for maximum subarray problem

**Comment by thepranaygupta** [comment]
assigned to @sejalrastogi

**Comment by PrabhuRaamDev** [comment]
I want to contribute to this project. Can you assign this to me?

**Comment by thepranaygupta** [comment]
@sejalrastogi are you working on this issue?
If not then I'll assign it to @PrabhuRaamDev
