### ISSUE TITLE
implement stack using LinkedList in C++

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#21]
implement stack using LinkedList in C++ [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/02.%20Stack/Basic%20Operation/2.%20Stack%20using%20LinkList)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by Nidhikumari-4** [comment]
please assign this issue to me

**Comment by parwez-zafar** [comment]
assign me this issue to me, I want to work on this issue.

**Comment by thepranaygupta** [comment]
assigned @Nidhikumari-4 and @parwez-zafar

**Comment by rustzz-27** [comment]
Hello,
can you assign this issue to me
Thank you

**Comment by Sahilnegi-code** [comment]
can I put the code of  find the mid of linked List.

**Comment by thepranaygupta** [comment]
> 
> 
> can I put the code of find the mid of linked List.

please create a new issue and I'll assign it to you 👍
