### ISSUE TITLE
implement stack using queue in C++

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#22]
implement stack using queue in C++ [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/02.%20Stack/Basic%20Operation/3.%20Stack%20using%20Queue)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by Nidhikumari-4** [comment]
please assign this issue to me

**Comment by rustzz-27** [comment]
Hello,
can you assign this issue to me
Thank you

**Comment by subhamengine** [comment]
i can do this!

**Comment by thepranaygupta** [comment]
@Nidhikumari-4 go for it!
