### ISSUE TITLE
C++ Solution for 3Sum Problem.

### ISSUE THREAD

**Issue by ayushjha952** [thepranaygupta/Data-Structures-and-Algorithms#226]
I would like to add the solution of the following [question](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/02.%20Algorithms/01.%20Arrays/12.%203Sum%20%2315) in c++.
@thepranaygupta Can you please assign it to me?

**Comment by thepranaygupta** [comment]
sure @ayushjha952 go for it 🚀

**Comment by ayushjha952** [comment]
@thepranaygupta can you please check the [PR](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/pull/231) once ?
