### ISSUE TITLE
Wave Array

### ISSUE THREAD

**Issue by shreya40** [thepranaygupta/Data-Structures-and-Algorithms#237]
Given a sorted array arr[] of distinct integers. Sort the array into a wave-like array and return it
In other words, arrange the elements into a sequence such that arr[1] >= arr[2] <= arr[3] >= arr[4] <= arr[5].....
example:
Input:
n = 5
arr[] = {1,2,3,4,5}
Output: 2 1 4 3 5
Explanation: Array elements after 
sorting it in wave form are 
2 1 4 3 5.

**Comment by thepranaygupta** [comment]
Assigned to @shreya40 🚀
