### ISSUE TITLE
implement Infix to Prefix in C++

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#32]
implement Infix to Prefix in C++ [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/02.%20Stack/Infix%20Prefix%20Postfix/02.%20Infix%20to%20Prefix)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by elementrix05** [comment]
Hello! I would love to work on this issue. Can you please assign it to me ?

**Comment by thepranaygupta** [comment]
go for it @elementrix05!
