### ISSUE TITLE
Include graph concept - Dijkstra Algorithm

### ISSUE THREAD

**Issue by adrishyantee** [thepranaygupta/Data-Structures-and-Algorithms#344]
Hello! I want to include Dijkstra's algorithm on how to find the shortest distance from the source and its solution in CPP in this repository. Please allow me to do so and assign the task under Hackactober fest.

**Comment by thepranaygupta** [comment]
@adrishyantee  are you working on this issue?

**Comment by jsabherwal** [comment]
I could work on it this week as she hasn't. I know these algorithms well because of my leetcode competition experience. I request you to assign this to me.

**Comment by thepranaygupta** [comment]
> 
> 
> I could work on it this week as she hasn't. I know these algorithms well because of my leetcode competition experience. I request you to assign this to me.

assigned to @jsabherwal

**Comment by jsabherwal** [comment]
Should be closed now, created a pull request with the implementation.
