### ISSUE TITLE
implement bubble sort in C and C++

### ISSUE THREAD

**Issue by 8-bit-souvik** [thepranaygupta/Data-Structures-and-Algorithms#38]

**Comment by 8-bit-souvik** [comment]
Hello! I would love to work on this issue. Can you please assign it to me ?

**Comment by 8-bit-souvik** [comment]
Hello! I am interested to work on this issue. Can you please assign it to me ?

**Comment by thepranaygupta** [comment]
assigned! @8-bit-souvik

**Comment by rustzz-27** [comment]
Hello can you assign it to me

**Comment by thepranaygupta** [comment]
> 
> 
> Hello can you assign it to me

sorry this issue is already assigned to someone, consider creating a new issue if you wish to contribute to the repository.
