### ISSUE TITLE
Range Sum of BST 

### ISSUE THREAD

**Issue by aritra-tech** [thepranaygupta/Data-Structures-and-Algorithms#388]
I want to add the Range Sum of BST Solution in Java, in the Leetcode Questions of the Tree folder. This question is asked in Amazon, Google, so it is important to add. Please assign this to me.

**Comment by LeTsC0D** [comment]
Please assign this task to me.
i will add the solution to 
Data-Structures-and-Algorithms\01. DataStructures\04. Tree\02. Binary Search Tree>

**Comment by SarojArchana** [comment]
could you please assign this issue to me.
