### ISSUE TITLE
implement Prefix to Infix in C++

### ISSUE THREAD

**Issue by thepranaygupta** [thepranaygupta/Data-Structures-and-Algorithms#69]
implement Prefix to Infix in C++ [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/02.%20Stack/Infix%20Prefix%20Postfix/04.%20Prefix%20to%20Infix)

comment under this issue to get assigned then commit your changes/updates in the respective directory.

Please **DO NOT** spam this repository with irrelevant PRs, or your PR will be marked as `invalid` or `spam`

**Comment by saiteja-2731** [comment]
Hey @thepranaygupta, Can I work on this?

**Comment by thepranaygupta** [comment]
Sure!
assigned to @saiteja-2731

**Comment by thepranaygupta** [comment]
> 
> 
> Hey @thepranaygupta, Can I work on this?

Amazing work!! 🥇
