### ISSUE TITLE
LoveBabbar sheet problem:- 188 Bottom view of a binary Tree

### ISSUE THREAD

**Issue by mukeshmjn** [thepranaygupta/Data-Structures-and-Algorithms#92]
@thepranaygupta PLEASE , assign this to me!

**Comment by divyavert** [comment]
can  u plz assign this to me

**Comment by gaurshraddha** [comment]
I can add cpp solution, plz assign this to me. I'd be grateful.

**Comment by mukeshmjn** [comment]
I'm working on cpp already I created this issue

**Comment by thepranaygupta** [comment]
assigned to @mukeshmjn 

@divyavert and @gaurshraddha issues are assigned on a first come first serve basis, if you wish to contribute you can create a new issue.
