### ISSUE TITLE
add Count Sort using C and C++ in algorithm

### ISSUE THREAD

**Issue by 8-bit-souvik** [thepranaygupta/Data-Structures-and-Algorithms#94]

**Comment by gaurshraddha** [comment]
Could you plz assign this to me? I'd add c++ solution.

**Comment by thepranaygupta** [comment]
assigned to @gaurshraddha

**Comment by 8-bit-souvik** [comment]
> Could you plz assign this to me? I'd add c++ solution.

Okay I'll add C solution
